### ISSUE TITLE
CH4 pip list shows a shorter list of installed packages

### ISSUE THREAD

**Issue by chadmando** [talkpython/data-driven-web-apps-with-pyramid-and-sqlalchemy#2]
Just started working through this course on Windows.  I noticed that in Chapter 4 after running the
 ```python setup.py develop```

My list of installed packages is much shorter than what is shown in the video. Just a Windows issue?  Maybe it will become clear as I make more progress.  Not sure if you have seen this before.

Here is my list:

> (venv) PS C:\Path\To\Project\pypi> pip list
> Package              Version Location
> 
> -------------------- ------- ----------------------------------------------------------------------------------------------------------------
> pip                  18.0
> pypi                 0.0     c:\Path\To\Project\pypi
> pyramid-chameleon    0.3
> pyramid-debugtoolbar 4.4
> setuptools           28.8.0
> waitress             1.1.0

**Comment by chadmando** [comment]
Update -- I moved from a PowerShell prompt to command line and more packages where installed.  My guess is that it was an Execution Policy issue within PowerShell.

**Comment by mikeckennedy** [comment]
Glad you solved it. I would have never known that powershell would be an issue!
