### ISSUE TITLE
Cookiecutter now requesting which db type (sqlalchemy, etc)

### ISSUE THREAD

**Issue by sollymay** [talkpython/data-driven-web-apps-with-pyramid-and-sqlalchemy#7]
Hey Michael,

Hope you are doing great! Happy holidays to you!

I have been following the starting part of this course, however Cookiecutter now added an option right after select template_language to select your database handler.

I selected sqlalchemy as I know it will be used throughout the course, however, when serving the website I am getting the following error, which is the website pyramid is serving to me (I also tried to follow the README.txt instructions without any luck)

```

Pyramid is having a problem using your SQL database.  The problem
might be caused by one of the following things:

1.  You may need to initialize your database tables with `alembic`.
    Check your README.txt for descriptions and try to run it.

2.  Your database server may not be running.  Check that the
    database server referred to by the "sqlalchemy.url" setting in
    your "development.ini" file is running.

After you fix the problem, please restart the Pyramid application to
try it again.
```

Any ideas on how to fix this?

**Comment by sollymay** [comment]
Hey Michael, I was able to fix this issue by selecting None (the default value for the backend handler, however it is important to highlight that change in the video

![screen shot 2018-12-24 at 11 31 27 pm](https://user-images.githubusercontent.com/6496698/50412248-0a5f7500-07d4-11e9-877e-f44fb7b033ca.png)

**Comment by mikeckennedy** [comment]
Hi @sollymay 

Thank you for the heads up. I'm glad you got it working but agree that it may trip some folks up. I just updated the video to have a little annotation (text) letting folks know to choose 1 for backend.

Check it out here around time: 3:15-3:30 or so:

https://training.talkpython.fm/player/course/building-data-driven-web-applications-in-python-with-pyramid-sqlalchemy-and-bootstrap/lecture/20402

Best,
Michael
