### ISSUE TITLE
db_session global_init static_method -> classmethod?

### ISSUE THREAD

**Issue by natter1** [talkpython/data-driven-web-apps-with-pyramid-and-sqlalchemy#8]
Compared to the flask sqlalchemy tutorial, in this tutorial you use a class DbSession in db_session.py (coming from an object oriented background, I prefer this - but is there a reasoning behind it?). I think, the global_init() method should not be declared static, as it changes the class DbSession (engine and factory). Therfore it should be a @classmethod imho? Its not a big issue, but since it is a tutorial, I really want to understand whats going on and why.

**Comment by mikeckennedy** [comment]
Hi @natter1 Thanks for the feedback. It's a good question. When I was working on this site, I was really more comfortable with objects and classes like you. But over time, I've come to appreciate that for classes that would basically be static only, the module can serve the same purpose when imported as a namespace.

```
from pypi.data import dbsession
# vs.
from pypi.data.dbsession import DbSession
```

and then using them:

```
dbsession.init()
# vs.
DbSession.init()
```

And in the end, the module style is simpler. If you were to create instances of the class, then it's clearly better that path, but it's kind of a wash here as used. But feel free to use either style. I've used both. :)
